# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-alacritty.toml */

[colors.primary]
background = '#131415'
foreground = '#FAEED6'

[colors.normal]
black   = '#3B3B3C'
red     = '#0D0F13'
green   = '#373E4B'
yellow  = '#A8474C'
blue    = '#9568B3'
magenta = '#858E99'
cyan    = '#B59B67'
white   = '#F0DFBC'

[colors.bright]
black   = '#A89C84'
red     = '#111419'
green   = '#495364'
yellow  = '#E05F65'
blue    = '#C68AEE'
magenta = '#B1BDCC'
cyan    = '#F1CF8A'
white   = '#F0DFBC'

[colors.cursor]
text   = '#131415'
cursor = '#A2A19D'
