# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Environment variables. See https://wiki.hyprland.org/Configuring/Environment-variables/

# Set your defaults editor through ENV in ~/.config/hypr/UserConfigs/01-UserDefaults.conf

### QT Variables ###
# env = QT_AUTO_SCREEN_SCALE_FACTOR,1
# env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
# env = QT_QPA_PLATFORMTHEME,qt5ct
# env = QT_QPA_PLATFORMTHEME,qt6ct

### xwayland apps scale fix (useful if you are use monitor scaling). ###
# Set same value if you use scaling in Monitors.conf
# 1 is 100% 1.5 is 150%
# see https://wiki.hyprland.org/Configuring/XWayland/
# env = GDK_SCALE,1
# env = QT_SCALE_FACTOR,1

### NVIDIA RTX Acceleration ###
# Configuração de alto desempenho para NVIDIA RTX e Wayland
# Veja: https://wiki.hyprland.org/Nvidia/#environment-variables
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = GBM_BACKEND,nvidia-drm
env = __GL_GSYNC_ALLOWED,1 # Adaptive Vsync / G-Sync
env = GSK_RENDERER,ngl

### Electron / Chromium & Firefox Wayland Optimization ###
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = MOZ_ENABLE_WAYLAND,1
env = EGL_PLATFORM,wayland

### Aquamarine Environment Variables (Hyprland > 0.45) ###
# env = AQ_TRACE,1
# env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0

### User Added ENVs ###
env = GTK_USE_PORTAL,1
env = GDK_DEBUG,portals
env = PATH,$HOME/.local/bin:$PATH
