# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Environment variables - Desktop Profile (NVIDIA RTX 5060)

### NVIDIA RTX Acceleration ###
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct
env = GBM_BACKEND,nvidia-drm
env = __GL_GSYNC_ALLOWED,1 # Adaptive Vsync / G-Sync
env = __GL_VRR_ALLOWED,1
env = GSK_RENDERER,ngl

### Electron / Chromium & Brave Wayland Optimization ###
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = BROWSER,brave
env = EGL_PLATFORM,wayland

### User Added ENVs ###
env = GTK_USE_PORTAL,1
env = GDK_DEBUG,portals
env = PATH,$HOME/.local/bin:$PATH

### GNOME Keyring & Secret Service ###
env = GNOME_KEYRING_CONTROL,$XDG_RUNTIME_DIR/keyring
env = SSH_AUTH_SOCK,$XDG_RUNTIME_DIR/keyring/ssh
