# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/
# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf
#
# Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this

input {
  kb_layout = us
  kb_variant = intl
  kb_options = caps:swapescape
  follow_mouse = 1
  sensitivity = 0
  touchpad {
    natural_scroll = true
  }
}

# Logitech K380 / K380s Bluetooth Keyboard explicit mapping
device {
  name = logitech-k380s-keyboard
  kb_layout = us
  kb_variant = intl
  kb_options = caps:swapescape
}

device {
  name = k380-keyboard
  kb_layout = us
  kb_variant = intl
  kb_options = caps:swapescape
}
