# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

windowrule = match:class ^(com.github.hluk.copyq)$, float on, center on, size (monitor_w*0.6) (monitor_h*0.7)
windowrule = match:class ^(floating_yazi)$, float on, center on, size (monitor_w*0.6) (monitor_h*0.7)
windowrule = match:class ^(yazi_picker)$, float on, center on, size (monitor_w*0.65) (monitor_h*0.75), stayfocused on
windowrule = match:class ^(com.github.wwmm.easyeffects)$, float on, center on, size (monitor_w*0.7) (monitor_h*0.7)
windowrule = match:class ^(gamescope)$, fullscreen on
windowrule = match:title ^(Picture-in-Picture)$, float on, pin on
windowrule = match:class ^([Vv]esktop)$, opacity 0.98
