[zram0]
# Cria swap ultra-rápido comprimido com ZSTD diretamente na memória RAM
# Elimina travamentos gerais de sistema (OOM freezes) sem desgastar o SSD
zram-size = min(ram / 2, 8192)
compression-algorithm = zstd
