[Display]
HiRes = TRUE
Fullscreen = FALSE
AspectRatio = TRUE
MaintainAspectRatio = TRUE
Scale = 3
Shader = 
BilinearFilter = TRUE

[Sound]
Sync = TRUE
Rate = 48000
BufferSize = 64

[Controls]
Joypad1 = TRUE
