# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# For window rules and layerrules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

# This file is used to add or overwrite window rules 
# This file will not be modified during dotfiles updates

windowrule = match:class ^(com.github.hluk.copyq)$, float on, center on, size (monitor_w*0.6) (monitor_h*0.7)
windowrule = match:class ^(floating_yazi)$, float on, center on, size (monitor_w*0.6) (monitor_h*0.7)
