[BitTorrent]
Session\ActiveDownloads=15
Session\ActiveTorrents=30
Session\ActiveUploads=4
Session\AdditionalTrackers="udp://tracker.opentrackr.org:1337/announce\nudp://open.demonii.com:1337/announce\nudp://open.stealth.si:80/announce\nudp://tracker.torrent.eu.org:451/announce\nudp://tracker.moeking.me:6969/announce\nudp://explodie.org:6969/announce\nudp://p4p.arenabg.ch:1337/announce\nudp://tracker.internetwarriors.net:1337\nudp://tracker.cyberia.is:6969/announce\nudp://retracker.lanta-net.ru:2710/announce\nudp://tracker.zerobytes.xyz:1337/announce\nudp://tracker.theoks.net:6969/announce\nudp://tracker.altrosky.nl:6969/announce"
Session\AsyncIOThreads=16
Session\AutoAddTrackers=true
Session\BTProtocol=Both
Session\CoalesceReadWrite=true
Session\DHT=true
Session\DiskCache=512
Session\DiskCacheTTL=60
Session\EnablePieceExtentAffinity=true
Session\Encryption=1
Session\GlobalMaxConns=1500
Session\GlobalMaxConnsPerTorrent=250
Session\GlobalMaxUploads=50
Session\GlobalMaxUploadsPerTorrent=10
Session\IgnoreLimitsOnLAN=true
Session\LSD=true
Session\MaxActiveDownloads=15
Session\MaxActiveTorrents=30
Session\MaxActiveUploads=4
Session\MaxConnections=1500
Session\MaxConnectionsPerTorrent=250
Session\MaxUploads=50
Session\MaxUploadsPerTorrent=10
Session\PeX=true
Session\Preallocation=true
Session\QueueingSystemEnabled=true
Session\SendBufferLowWatermark=10240
Session\SendBufferWatermark=20480
Session\SendBufferWatermarkFactor=150
Session\Subcategories=true
Session\ValidateHTTPSTrackerCertificate=false

[Core]
AutoConfiguration=true

[Downloads]
DiskWriteCacheSize=512
PreAllocateAllFiles=true
SavePath=/mnt/dados/05_Midias_Design_e_Criacao/Videos/Downloads
ScanDirsV2=@Invalid()
TempPathEnabled=false

[General]
CloseToTray=true
CustomUIThemePath=~/.config/qBittorrent/themes/catppuccin-mocha.qbtheme
MinimizeToTray=true
NoSplashScreen=true
PreventFromSuspendWhenDownloading=true
StartMinimized=false
UseCustomUITheme=true

[Network]
Cookies=@Invalid()
PortRangeMin=6881
UPnP=true
