[General]
# Garante que o Bluetooth sempre ligue ativo no boot sem cliques manuais
AutoEnable=true

# Reduz tempo de conexão de fones/teclados para menos de 1 segundo
FastConnectable=true

# Reconexão rápida e estável com dispositivos conhecidos
JustWorksRepairing=always
Privacy=device
