# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# 🖥️ Configuração de Monitores (Lenovo ThinkPad T480)

# Tela Integrada do ThinkPad T480 (Full HD 1920x1080 @ 60Hz)
monitor = eDP-1, 1920x1080@60, 0x0, 1

# Fallbacks automáticos para monitores externos conectados via HDMI ou USB-C / Thunderbolt
monitor = , preferred, auto, 1
