# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# 🖥️ Configuração de Monitores (Dual Monitor Gold Setup)
monitor = DP-1, 1920x1080@99.65, 1920x0, 1
monitor = HDMI-A-1, 1920x1080@74.97, 0x0, 1
monitor = , preferred, auto, 1
