# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# 🪟 Regras de Workspaces (HDMI-A-1 no Workspace 1 e DP-1 com Workspaces 2 a 10)

# ==============================================================================
# MONITOR SECUNDÁRIO (HDMI-A-1) - Fixo no Workspace 1
# ==============================================================================
workspace = 1, monitor:HDMI-A-1, default:true

# ==============================================================================
# MONITOR PRIMÁRIO (DP-1 - 100Hz Principal) - Workspaces de Produção 2 a 10
# ==============================================================================
workspace = 2, monitor:DP-1, default:true
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-1
workspace = 7, monitor:DP-1
workspace = 8, monitor:DP-1
workspace = 9, monitor:DP-1
workspace = 10, monitor:DP-1
