# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# 🪟 Regras de Workspaces - Lenovo ThinkPad T480 (Display eDP-1)
# Todos os workspaces (1 a 10) vinculados de forma estável à tela do laptop

workspace = 1, monitor:eDP-1, default:true
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:eDP-1
