# Desativa suspensão automática dos nós de áudio ALSA por inatividade
# Elimina delay (atraso) no início da reprodução e estalos mecânicos ("pops") em DACs e fones
monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_input.*"
      },
      {
        node.name = "~alsa_output.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
