[manager]
ratio          = [ 1, 4, 3 ]
sort_by        = "alphabetical"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
show_hidden    = true
show_symlink   = true

[preview]
tab_size        = 2
max_width       = 600
max_height      = 900
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
edit = [
	{ run = '${EDITOR:-vi} "$@"', block = true, desc = "Edit" },
]
pdf = [
	{ run = 'okular "$@"', orphan = true, desc = "Okular (PDF & Anotações)" },
	{ run = 'zathura "$@"', orphan = true, desc = "Zathura (Vim PDF Rápido)" },
]
video = [
	{ run = 'celluloid "$@"', orphan = true, desc = "Celluloid (MPV Moderno)" },
	{ run = 'mpv "$@"', orphan = true, desc = "MPV" },
]
office = [
	{ run = 'onlyoffice-desktopeditors "$@"', orphan = true, desc = "OnlyOffice" },
]

[open]
rules = [
	{ mime = "inode/directory", use = [ "open", "edit" ] },
	{ mime = "text/*", use = [ "edit", "open" ] },
	{ mime = "image/*", use = [ "open" ] },
	{ mime = "video/*", use = [ "video", "open" ] },
	{ mime = "audio/*", use = [ "video", "open" ] },
	{ mime = "application/pdf", use = [ "pdf", "open" ] },
	{ mime = "application/vnd.openxmlformats-officedocument.*", use = [ "office", "open" ] },
	{ mime = "application/msword", use = [ "office", "open" ] },
	{ mime = "application/vnd.ms-*", use = [ "office", "open" ] },
]


[flavor]
use = "catppuccin-mocha"
