# ==============================================================================
# 🎮 PIPEWIRE PULSEAUDIO LATENCY & STABILITY (Discord, Games, Spotify, Browsers)
# ==============================================================================
pulse.properties = {
    pulse.min.req          = 32/48000
    pulse.default.req      = 1024/48000
    pulse.max.req          = 2048/48000
    pulse.min.quantum      = 32/48000
}
