--ozone-platform-hint=auto
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,CanvasOopRasterization,TouchpadOverscrollHistoryNavigation
--enable-gpu-rasterization
--enable-zero-copy
--ignore-gpu-blocklist
--password-store=gnome-libsecret
