--ozone-platform-hint=auto
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,CanvasOopRasterization,TouchpadOverscrollHistoryNavigation,ParallelDownloading,BackForwardCache
--enable-smooth-scrolling
--enable-gpu-rasterization
--ignore-gpu-blocklist
--enable-accelerated-video-decode
--enable-accelerated-2d-canvas
--disable-background-timer-throttling
--disable-backgrounding-occluded-windows
--password-store=gnome-libsecret
