--ozone-platform-hint=auto
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,CanvasOopRasterization,TouchpadOverscrollHistoryNavigation,ParallelDownloading,BackForwardCache,AcceleratedVideoDecodeLinuxGL
--enable-blink-features=MiddleClickAutoscroll
--enable-smooth-scrolling
--enable-gpu-rasterization
--enable-zero-copy
--ignore-gpu-blocklist
--enable-accelerated-video-decode
--enable-accelerated-2d-canvas
--password-store=gnome-libsecret
--use-gl=angle
--use-angle=vulkan
