# ⌨️ Yazi Keymap - Antigravity Edition

[[manager.prepend_keymap]]
on   = [ "a", "e" ]
run  = 'shell "ouch decompress \"$@\"" --block --confirm'
desc = "Extrair arquivos com ouch"

[[manager.prepend_keymap]]
on   = [ "a", "c" ]
run  = 'shell "ouch compress \"$@\" \"${1##*/}.zip\"" --block --confirm'
desc = "Compactar arquivos para .zip com ouch"

[[manager.prepend_keymap]]
on   = [ "y" ]
run  = 'shell "echo -n \"$@\" | wl-copy" --confirm'
desc = "Copiar caminho do arquivo"

[[manager.prepend_keymap]]
on   = [ "T" ]
run  = 'shell "$SHELL" --block'
desc = "Abrir terminal aqui"
