player: mpris

mpris:
  players:
    - spotify
    - amberol
    - Amberol
    - io.bassi.Amberol

local:
  folder: "/mnt/dados/05_Midias_Design_e_Criacao/Musicas_e_Audios/Downloads"

style:
  hAlignment: center
  before:
    foreground: "#a6adc8"
    bold: false
    faint: true
  current:
    foreground: "#a6e3a1"
    bold: true
  after:
    foreground: "#6c7086"
    faint: true
