[General]
plugin_priority=itemimage, itemencrypted, itemfakevim, itemnotes, itempinned, itemsync, itemtags, itemtext

[Options]
action_has_input=false
action_has_output=false
action_output_tab=
action_separator=\\n
activate_closes=true
activate_focuses=true
activate_pastes=true
always_on_top=false
autocompletion=true
autostart=false
check_clipboard=true
check_selection=false
clipboard_notification_lines=0
clipboard_tab=&clipboard
close_on_unfocus=true
command_history_size=100
confirm_exit=true
copy_clipboard=false
copy_selection=false
disable_tray=false
edit_multiline=false
editor=nvim %1
expire_tab=0
hide_main_window=true
hide_main_window_in_task_bar=true
hide_tabs=false
hide_toolbar=true
hide_toolbar_labels=true
item_data_threshold=1024
max_items=1000
move=true
native_menu_bar=false
notification_horizontal_offset=10
notification_maximum_height=100
notification_maximum_width=300
notification_position=3
notification_vertical_offset=10
number_search=false
open_windows_on_current_screen=true
save_delay_ms_on_item_added=300
save_delay_ms_on_item_edited=1000
save_delay_ms_on_item_modified=300
save_delay_ms_on_item_moved=1800
save_delay_ms_on_item_removed=600
save_filter_history=false
show_advanced_command_settings=false
show_simple_items=false
show_tab_item_count=false
tab_tree=false
tabs=&clipboard
text_tab=
text_wrap=true
transient_display_time=0
tray_commands=true
tray_images=true
tray_item_paste=true
tray_items=5
tray_tab=
tray_tab_is_current=true
vi=false

[Theme]
alt_bg=#1e1e2e
alt_item_css=
bg=#181825
css=
cur_item_css=
edit_bg=#1e1e2e
edit_fg=#cdd6f4
edit_font="Sans,10,-1,5,50,0,0,0,0,0"
fg=#cdd6f4
find_bg=#f9e2af
find_fg=#11111b
find_font="Sans,10,-1,5,50,0,0,0,0,0"
font="Sans,10,-1,5,50,0,0,0,0,0"
font_antialiasing=true
hover_item_css=
icon_color=#89b4fa
item_css=
item_spacing=
menu_bar_css=
menu_bar_disabled_css=
menu_bar_selected_css=
menu_css=
notes_bg=#1e1e2e
notes_css=
notes_fg=#cdd6f4
notes_font="Sans,10,-1,5,50,0,0,0,0,0"
notification_bg=#1e1e2e
notification_fg=#cdd6f4
notification_font="Sans,10,-1,5,50,0,0,0,0,0"
num_fg=#6c7086
num_font="Sans,8,-1,5,50,0,0,0,0,0"
search_bar=
search_bar_focused=
sel_bg=#313244
sel_fg=#cdd6f4
sel_item_css=
show_number=true
show_scrollbars=true
style_main_window=false
tab_bar_css=
tab_bar_item_counter_css=
tab_bar_scroll_buttons_css=
tab_bar_sel_item_counter_css=
tab_bar_tab_selected_css=
tab_tree_css=
tab_tree_item_counter_css=
tab_tree_sel_item_counter_css=
tab_tree_tab_selected_css=
tool_bar_css=
tool_button_css=
tool_button_pressed_css=
tool_button_selected_css=
use_system_icons=false
