# Impede que fones de ouvido Bluetooth (AirPods, Galaxy Buds, etc.)
# mudem automaticamente para codec de baixa qualidade telefônica (HFP) em chamadas
wireplumber.settings = {
    bluetooth.autoswitch-to-headset-profile = false
}
